name = "ids"
version = "0.11.0"
licences = ["Apache-2.0"]
description = "âœ¨ Unique IDs for Gleam"
repository = { type = "github", user = "rvcas", repo = "ids" }
gleam = ">= 0.32.2"

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_otp = "~> 0.7"
gleam_erlang = "~> 0.22"

[dev-dependencies]
gleeunit = "~> 1.0"
