name = "ids"
version = "0.7.0"
licences = ["Apache-2.0"]
description = "âœ¨ Unique IDs for Gleam"
repository = { type = "github", user = "rvcas", repo = "ids" }

[dependencies]
gleam_stdlib = "~> 0.28"
gleam_otp = "~> 0.5"
gleam_erlang = "~> 0.18"

[dev-dependencies]
gleeunit = "~> 0.10"
